### PR TITLE
Add ability to host via Docker

### PR DESCRIPTION
**Pull request by stefanv**
Two docker containers are launched: db, for postgresql, and thresher_api, for
the Django API.  A script "init_docker.sh" is provided to initialize the
database.

**NOTE** #10 first has to be merged

### CODE REVIEW

**Comment by stefanv** [comment]
@secant @floraxue I've noticed that the schema_parser is currently broken.  Do you want to take a look?

```
loading schema: Events
loading schema: Protester
load_data.py:65: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if article['text'] != existing_article.text:

NEW ID! 20000
Traceback (most recent call last):
  File "load_data.py", line 167, in <module>
    load_article_dir(args.article_dir)
  File "load_data.py", line 130, in load_article_dir
    load_article(parse_document(os.path.join(dirpath, article_file)))
  File "load_data.py", line 112, in load_article
    tua_id=tua_id,
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 417, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'analysis_type' is an invalid keyword argument for this function
```

I suspect some of the refactorings you did did not make it into the merged pull request.  Please find them and submit another PR.

**Comment by secant** [comment]
@stefanv Will take a look right now!

**Comment by secant** [comment]
@stefanv Opened #13, which fixes the parser + updates our data model.

**Comment by stefanv** [comment]
@secant @floraxue I've updated this PR.  Please try and get it working on your systems according to the instructions in the README.

@secant Note that I had to make a few fixes to get the new SchemaTopics to serialize.

**Pull request merged**
